mutation CreateSeedData @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it is only used for initial data seeding in a non-production environment.") @transaction {
  user_insertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      username: "demouser1",
      email: "demouser1@example.com",
      createdAt: "2024-01-01T00:00:00Z"
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      username: "demouser2",
      email: "demouser2@example.com",
      createdAt: "2024-01-01T00:00:00Z"
    }
  ])
  comment_insertMany(data: [
    {
      user: "550e8400-e29b-41d4-a716-446655440000",
      content: "Example comment from demouser1",
      createdAt: "2024-01-02T00:00:00Z"
    },
    {
      user: "550e8400-e29b-41d4-a716-446655440001",
      content: "Example comment from demouser2",
      createdAt: "2024-01-02T00:00:00Z"
    }
  ])
}